export interface Card {
    id: string;
    text: string;
    type: 'challenge' | 'question' | 'rule' | 'viral';
    mode: 'binary' | 'statement' | 'rule'; // binary = Yes/No, statement = OK/Applies to me, rule = Accept
    drinkTrigger?: 'yes' | 'no' | 'always' | 'none';
    drinkAction?: string; // e.g. "Bebe 2 tragos"
    points?: number; // Points awarded for this card (default 1)
    specialEffect?: 'double' | 'reverse' | 'skip' | 'steal'; // Special game mechanics
}

export const GAME_CARDS: Card[] = [
    // --- CLICHÉS & PREGUNTAS (Binary: Yes/No) ---
    {
        id: 'c1',
        text: '¿Te has enamorado alguna vez de tu mejor amiga?',
        type: 'question',
        mode: 'binary',
        drinkTrigger: 'yes',
        drinkAction: 'Bebe por intensa',
    },
    {
        id: 'c2',
        text: '¿Te has liado con una profesora?',
        type: 'question',
        mode: 'binary',
        drinkTrigger: 'yes',
    },
    {
        id: 'c3',
        text: '¿Sigues hablando con tu ex casi a diario?',
        type: 'question',
        mode: 'binary',
        drinkTrigger: 'yes',
        drinkAction: 'Bebe y bloqueala',
    },
    {
        id: 'c4',
        text: '¿Tienes algún tatuaje que te hiciste por una novia?',
        type: 'question',
        mode: 'binary',
        drinkTrigger: 'yes',
    },
    {
        id: 'c5',
        text: '¿Has llorado en una discoteca este año?',
        type: 'question',
        mode: 'binary',
        drinkTrigger: 'yes',
    },
    {
        id: 'c6',
        text: '¿Te has mudado con alguien antes de los 3 meses?',
        type: 'question',
        mode: 'binary',
        drinkTrigger: 'yes',
        drinkAction: 'Bebe un fondo',
    },
    {
        id: 'c7',
        text: '¿Alguna vez has salido con alguien que se llamaba igual que tú?',
        type: 'question',
        mode: 'binary',
        drinkTrigger: 'yes',
    },
    {
        id: 'c8',
        text: '¿Has tenido una cita en IKEA?',
        type: 'question',
        mode: 'binary',
        drinkTrigger: 'yes',
    },
    {
        id: 'c9',
        text: '¿Tienes gatos?',
        type: 'question',
        mode: 'binary',
        drinkTrigger: 'no',
        drinkAction: 'Si NO tienes gatos, bebe. ¡Raro!',
    },
    {
        id: 'c10',
        text: '¿Has revisado el horóscopo de tu crush para ver la compatibilidad?',
        type: 'question',
        mode: 'binary',
        drinkTrigger: 'yes',
    },
    {
        id: 'c11',
        text: '¿Has escrito una carta de amor a mano en el último año?',
        type: 'question',
        mode: 'binary',
        drinkTrigger: 'yes',
    },
    {
        id: 'c12',
        text: '¿Has estado en una relación a distancia con alguien de otro continente?',
        type: 'question',
        mode: 'binary',
        drinkTrigger: 'yes',
    },

    // --- REGLAS & ESTADOS (Statement: Applies to me / Everyone check) ---
    {
        id: 'r1',
        text: 'Bebe un trago por cada anillo que lleves puesto ahora mismo.',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'always',
    },
    {
        id: 'r2',
        text: 'Si tienes los ojos azules o verdes, bebe.',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'always',
    },
    {
        id: 'r3',
        text: 'Si llevas puesto algo de cuadros (camisa, pantalones...), bebe.',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'always',
    },
    {
        id: 'r4',
        text: 'La persona con el pelo más corto del grupo manda beber a quien quiera.',
        type: 'challenge',
        mode: 'statement',
        drinkTrigger: 'none',
    },
    {
        id: 'r5',
        text: 'Quien tenga más ex-novias en el grupo, bebe 2 tragos.',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'always',
    },

    // --- RETOS Y JUEGOS TEMPORALES (Rule: Accepts challenge) ---
    {
        id: 'g1',
        text: 'Durante esta ronda, NO puedes decir "Sí" ni "No". Si lo dices, bebes.',
        type: 'rule',
        mode: 'rule',
        drinkTrigger: 'none',
    },
    {
        id: 'g2',
        text: 'Habla con acento extranjero hasta que te vuelva a tocar el turno. Si se te olvida, bebe.',
        type: 'rule',
        mode: 'rule',
        drinkTrigger: 'none',
    },
    {
        id: 'g3',
        text: 'Debes beberle la copa a alguien del local (o del grupo) los sorbos que te digan.',
        type: 'challenge',
        mode: 'statement',
        drinkTrigger: 'always',
    },
    {
        id: 'g4',
        text: 'Enséñale a la persona de tu derecha la última foto de tu galería o bebe todo tu vaso.',
        type: 'challenge',
        mode: 'binary',
        drinkTrigger: 'no', // Choice: Show photo (Yes/Safe) or Drink (No)
        drinkAction: '¡A beber el vaso entero!',
    },
    {
        id: 'g5',
        text: 'Manda un mensaje a tu crush o ex ahora mismo. Si no te atreves, bebe.',
        type: 'challenge',
        mode: 'binary',
        drinkTrigger: 'no',
        drinkAction: 'Bebe por cobarde',
    },

    // --- USER SUBMITTED: YO NUNCA (Bollera Version) ---
    {
        id: 'u1',
        text: 'Yo nunca me he mudado con alguien antes de los 3 meses "porque todo fluía".',
        type: 'question',
        mode: 'binary',
        drinkTrigger: 'yes',
        drinkAction: 'Bebe, U-Haul',
    },
    {
        id: 'u2',
        text: 'Yo nunca he dicho "somos solo amigas" cuando NO éramos solo amigas.',
        type: 'question',
        mode: 'binary',
        drinkTrigger: 'yes',
    },
    {
        id: 'u3',
        text: 'Yo nunca he stalkeado a la ex de mi crush más que a mi propia familia.',
        type: 'question',
        mode: 'binary',
        drinkTrigger: 'yes',
        drinkAction: 'Bebe por FBI',
    },
    {
        id: 'u4',
        text: 'Yo nunca he llevado tote bag como si fuera una extensión de mi alma.',
        type: 'question',
        mode: 'binary',
        drinkTrigger: 'yes',
    },
    {
        id: 'u5',
        text: 'Yo nunca he dicho "no quiero nada serio" y he acabado con cepillo de dientes en su casa.',
        type: 'question',
        mode: 'binary',
        drinkTrigger: 'yes',
    },
    {
        id: 'u6',
        text: 'Yo nunca he tenido una "mejor amiga" que en realidad era mi rollo.',
        type: 'question',
        mode: 'binary',
        drinkTrigger: 'yes',
    },
    {
        id: 'u7',
        text: 'Yo nunca he caído en la trampa de la chica con guitarra.',
        type: 'question',
        mode: 'binary',
        drinkTrigger: 'yes',
    },
    {
        id: 'u8',
        text: 'Yo nunca he vuelto con una ex "solo para hablar".',
        type: 'question',
        mode: 'binary',
        drinkTrigger: 'yes',
        drinkAction: 'Bebe, que no te lo crees ni tú',
    },
    {
        id: 'u9',
        text: 'Yo nunca he dicho "esto es solo un café" sabiendo perfectamente que no lo era.',
        type: 'question',
        mode: 'binary',
        drinkTrigger: 'yes',
    },
    {
        id: 'u10',
        text: 'Yo nunca he tenido un flechazo por una camarera solo porque me sonrió.',
        type: 'question',
        mode: 'binary',
        drinkTrigger: 'yes',
        drinkAction: 'Bebe por ilusa',
    },

    // --- USER SUBMITTED: RETOS / ACCIONES ---
    {
        id: 'u11',
        text: 'Dile a tu derecha cuándo fue la última vez que te enamoraste en 48 horas.',
        type: 'challenge',
        mode: 'statement',
        drinkTrigger: 'none',
    },
    {
        id: 'u12',
        text: 'Tienes 30 segundos para improvisar una canción dramática estilo cantautora lesbiana.',
        type: 'challenge',
        mode: 'statement',
        drinkTrigger: 'none',
    },
    {
        id: 'u13',
        text: 'Confiesa a quién del grupo meterías en tu U-Haul ficticia.',
        type: 'challenge',
        mode: 'statement',
        drinkTrigger: 'none',
    },
    {
        id: 'u14',
        text: 'Haz una declaración de amor súper intensa a alguien al azar… como si llevarais 2 meses saliendo.',
        type: 'challenge',
        mode: 'statement',
        drinkTrigger: 'none',
    },
    {
        id: 'u15',
        text: 'Imita a una bollera intentando ligar tímidamente en un bar.',
        type: 'challenge',
        mode: 'statement',
        drinkTrigger: 'none',
    },
    {
        id: 'u16',
        text: 'Di el nombre de tu ex más caótica sin reírte. Si te ríes, bebes.',
        type: 'challenge',
        mode: 'binary',
        drinkTrigger: 'no', // Binary here acts as Success/Fail logic roughly, or just statement
        drinkAction: '¡Bebes por reírte del trauma!',
    },
    {
        id: 'u17',
        text: 'Describe tu tipo de chica ideal solo usando clichés.',
        type: 'challenge',
        mode: 'statement',
        drinkTrigger: 'none',
    },
    {
        id: 'u18',
        text: 'Cuenta tu anécdota más "esto solo le pasa a una bollera".',
        type: 'challenge',
        mode: 'statement',
        drinkTrigger: 'none',
    },
    {
        id: 'u19',
        text: 'Muestra tu pose típica cuando te gusta una chica (spoiler: manos en los bolsillos).',
        type: 'challenge',
        mode: 'statement',
        drinkTrigger: 'none',
    },
    {
        id: 'u20',
        text: 'Di tres señales universales de que una chica es bollera. Si fallas, bebes doble.',
        type: 'challenge',
        mode: 'statement',
        drinkTrigger: 'none',
    },

    // --- USER SUBMITTED: CLICHÉS & MINI-HISTORIAS (Bebe si...) ---
    {
        id: 'u21',
        text: 'Bebe si alguna vez te has enamorado de tu amiga hetero por accidente.',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'always',
    },
    {
        id: 'u22',
        text: 'Bebe si alguna vez has salido con alguien que tenía más plantas que espacio vital.',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'always',
    },
    {
        id: 'u23',
        text: 'Bebe si has tenido una relación que empezó con: "No busco nada serio". Spoiler: duró un año.',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'always',
    },
    {
        id: 'u24',
        text: 'Bebe si has usado la palabra "energía" para justificar un flechazo.',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'always',
    },
    {
        id: 'u25',
        text: 'Bebe si has tenido que explicar que no todas las lesbianas se conocen entre sí… y luego sí la conocías.',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'always',
    },
    {
        id: 'u26',
        text: 'Bebe si tuviste una fase camisa de leñador.',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'always',
    },
    {
        id: 'u27',
        text: 'Bebe si tuviste un crush por una profe, monitora o entrenadora.',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'always',
    },
    {
        id: 'u28',
        text: 'Bebe si te has enamorado por cómo te habló de su gata.',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'always',
    },
    {
        id: 'u29',
        text: 'Bebe si alguna vez has ligado gracias a un piercing o un corte de pelo sospechoso.',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'always',
    },
    {
        id: 'u30',
        text: 'Bebe quien haya tenido una relación que empezó con un match y terminó con una mudanza.',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'always',
    },
    {
        id: 'u31',
        text: 'Bebe quien haya caído en una chica con trauma y talento artístico.',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'always',
    },
    {
        id: 'u32',
        text: 'Bebe quien haya dicho "esto es diferente" y no era diferente.',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'always',
    },

    // --- GENERATED EXPANSION (More Content) ---
    {
        id: 'gen1',
        text: 'Bebe si tienes un manojo de llaves colgado del pantalón ahora mismo.',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'always',
    },
    {
        id: 'gen2',
        text: 'Yo nunca he llorado viendo "Carol" o "Retrato de una mujer en llamas".',
        type: 'question',
        mode: 'binary',
        drinkTrigger: 'yes',
    },
    {
        id: 'gen3',
        text: 'Bebe si tu bebida favorita es un Iced Coffee, haga frío o calor.',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'always',
    },
    {
        id: 'gen4',
        text: 'Yo nunca he revisado la carta astral de alguien antes de la primera cita.',
        type: 'question',
        mode: 'binary',
        drinkTrigger: 'yes',
        drinkAction: 'Bebe, bruja',
    },
    {
        id: 'gen5',
        text: 'Menciona 3 personajes de The L Word en 5 segundos. Si fallas, bebes.',
        type: 'challenge',
        mode: 'statement',
        drinkTrigger: 'none',
    },
    {
        id: 'gen6',
        text: 'Bebe si tienes las uñas cortas. (Ya sabemos por qué).',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'always',
    },
    {
        id: 'gen7',
        text: 'Yo nunca he tenido un crush con Zendaya o Kristen Stewart.',
        type: 'question',
        mode: 'binary',
        drinkTrigger: 'yes',
        drinkAction: 'Bebe, es inevitable',
    },
    {
        id: 'gen8',
        text: 'Llama a tu madre (o figura materna) y dile que la quieres. Si no, trago largo.',
        type: 'challenge',
        mode: 'statement',
        drinkTrigger: 'none',
    },
    {
        id: 'gen9',
        text: 'Bebe si has conducido más de 1 hora solo para ver a un ligue.',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'always',
    },
    {
        id: 'gen10',
        text: 'Intercambia una prenda de ropa con la persona de tu izquierda. Si no queréis, bebed las dos.',
        type: 'challenge',
        mode: 'statement',
        drinkTrigger: 'none',
    },
    {
        id: 'gen11',
        text: 'Bebe si llevas Vans, Doc Martens o Converse ahora mismo.',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'always',
    },
    {
        id: 'gen12',
        text: 'Yo nunca he fingido que me gusta el horóscopo para ligar.',
        type: 'question',
        mode: 'binary',
        drinkTrigger: 'yes',
    },
    {
        id: 'gen13',
        text: 'Bebe si alguna vez te han imaginado casandote con alguien que hacia menos de dos meses que estabas conociendo.',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'always',
    },
    {
        id: 'gen14',
        text: 'Yo nunca he salido con la ex de una amiga.',
        type: 'question',
        mode: 'binary',
        drinkTrigger: 'yes',
        drinkAction: 'Bebe, el círculo es pequeño',
    },
    {
        id: 'gen15',
        text: 'Haz un brindis por todas las veces que nos rompieron el corazón. Todas beben.',
        type: 'viral',
        mode: 'rule',
        drinkTrigger: 'always',
    },
    {
        id: 'gen16',
        text: 'Bebe si tienes un tatuaje de una planta, luna, sol o algo místico.',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'always',
    },
    {
        id: 'gen17',
        text: 'Yo nunca he pensado que sería buena idea cortarme el pelo yo misma a las 3 AM.',
        type: 'question',
        mode: 'binary',
        drinkTrigger: 'yes',
    },
    {
        id: 'gen18',
        text: 'Elige a alguien para hacer un pulso. La que pierda, bebe.',
        type: 'challenge',
        mode: 'statement',
        drinkTrigger: 'none',
    },
    {
        id: 'gen19',
        text: 'Bebe si has estado en un "situationship" de más de 6 meses.',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'always',
    },
    {
        id: 'gen20',
        text: 'Yo nunca he dudado de mi sexualidad otra vez después de ver a un hombre guapo (y luego se me pasó a los 2 segundos).',
        type: 'question',
        mode: 'binary',
        drinkTrigger: 'yes',
    },
    {
        id: 'gen21',
        text: 'Bebe si sigues a más de 5 cuentas de gatos/perros en Instagram.',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'always',
    },
    {
        id: 'gen22',
        text: 'Señala a la persona que crees que liga más. La más señalada bebe.',
        type: 'challenge',
        mode: 'statement',
        drinkTrigger: 'none',
    },
    {
        id: 'gen23',
        text: 'Yo nunca he ido a un bar gay y me he sentido vieja.',
        type: 'question',
        mode: 'binary',
        drinkTrigger: 'yes',
    },
    {
        id: 'gen24',
        text: 'Bebe si tu "type" es emocionalmente no disponible.',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'always',
    },
    {
        id: 'gen25',
        text: 'Imita a un personaje famosos, quien adivine no bebe.',
        type: 'challenge',
        mode: 'binary',
        drinkTrigger: 'no',
    },
    {
        id: 'gen26',
        text: 'Bebe si has dicho "es complicado" cuando te preguntaron por tu estado civil.',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'always',
    },
    {
        id: 'gen27',
        text: 'Yo nunca he tenido una cita que duró todo el fin de semana.',
        type: 'question',
        mode: 'binary',
        drinkTrigger: 'yes',
    },
    {
        id: 'gen28',
        text: 'Si llevas un mosquetón, reparte 2 tragos.',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'none',
    },
    {
        id: 'gen29',
        text: 'Bebe si tienes una playlist para llorar y otra para empoderarte.',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'always',
    },
    {
        id: 'gen30',
        text: 'Yo nunca he comprado entradas para un concierto de una artista indie 6 meses antes.',
        type: 'question',
        mode: 'binary',
        drinkTrigger: 'yes',
    },
    {
        id: 'gen31',
        text: '¿Vegetariana o vegana? Si sí, manda beber a una carnívora.',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'none',
    },
    {
        id: 'gen32',
        text: 'Bebe si tienes un piercing en la nariz (septum o nostril).',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'always',
    },
    {
        id: 'gen33',
        text: 'Yo nunca he idealizado una relación con alguien con quien solo he cruzado 2 palabras.',
        type: 'question',
        mode: 'binary',
        drinkTrigger: 'yes',
    },
    {
        id: 'gen34',
        text: 'Bebe si te sabes que debe llevar toda lesbiana en una cita. La minoría bebe.',
        type: 'challenge',
        mode: 'statement',
        drinkTrigger: 'none',
    },
    {
        id: 'gen35',
        text: 'Di una verdad dolorosa sobre tu vida amorosa o bebe.',
        type: 'challenge',
        mode: 'binary',
        drinkTrigger: 'no',
    },
    {
        id: 'gen36',
        text: 'Bebe si alguna vez te han dicho "es que no pareces lesbiana".',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'always',
    },
    {
        id: 'gen37',
        text: 'Yo nunca he intentado convencer a una amiga de que deje a su novio.',
        type: 'question',
        mode: 'binary',
        drinkTrigger: 'yes',
    },
    {
        id: 'gen38',
        text: 'Bebe si tienes más de 3 camisas de botones estampadas.',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'always',
    },
    {
        id: 'gen39',
        text: 'Si reconoces la frase "We fell in love in October", bebe.',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'always',
    },
    {
        id: 'gen40',
        text: 'Tira una moneda. Cara tú bebes, Cruz eliges quién bebe.',
        type: 'challenge',
        mode: 'statement',
        drinkTrigger: 'none',
    },

    // ==========================================
    // CULTURA POP SÁFICA (Movies, Music, TV)
    // ==========================================
    {
        id: 'pop1',
        text: 'Bebe si has visto "The L Word" entera más de una vez.',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'always',
    },
    {
        id: 'pop2',
        text: 'Yo nunca he shippeado a dos amigas en una serie que NO eran canon (Rizzoli & Isles, Supercorp...).',
        type: 'question',
        mode: 'binary',
        drinkTrigger: 'yes',
        drinkAction: 'Bebe por ilusa',
    },
    {
        id: 'pop3',
        text: 'Canta el estribillo de una canción de t.A.T.u. Si no te la sabes, bebe.',
        type: 'challenge',
        mode: 'statement',
        drinkTrigger: 'none',
    },
    {
        id: 'pop4',
        text: 'Bebe si tu despertar sexual fue Xena, Shego o Mulán.',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'always',
    },
    {
        id: 'pop5',
        text: 'Yo nunca he llorado con el final de "La vida de Adèle" (aunque sea problemática).',
        type: 'question',
        mode: 'binary',
        drinkTrigger: 'yes',
    },
    {
        id: 'pop6',
        text: 'Bebe si sigues a Fletcher en Instagram.',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'always',
    },
    {
        id: 'pop7',
        text: '¿Quién es la más organizada? La que señalen la mayoría bebe.',
        type: 'challenge',
        mode: 'statement',
        drinkTrigger: 'none',
    },
    {
        id: 'pop8',
        text: 'Yo nunca he visto "Orange Is the New Black" solo por Alex Vause.',
        type: 'question',
        mode: 'binary',
        drinkTrigger: 'yes',
    },
    {
        id: 'pop9',
        text: 'Bebe si sabes quién es Ana Legazpi.',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'always',
    },
    {
        id: 'pop10',
        text: 'Confiesa: ¿Team Shane o Team Carmen? Si dices Tina, bebes doble.',
        type: 'challenge',
        mode: 'statement',
        drinkTrigger: 'none',
    },
    {
        id: 'pop11',
        text: 'Bebe si has visto "Gentleman Jack".',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'always',
    },
    {
        id: 'pop12',
        text: 'Yo nunca he buscado "películas lésbicas en Netflix" un viernes por la noche.',
        type: 'question',
        mode: 'binary',
        drinkTrigger: 'yes',
    },
    {
        id: 'pop13',
        text: 'Bebe si alguna vez te has disfrazado de un personaje sáfico en Halloween.',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'always',
    },
    {
        id: 'pop14',
        text: 'Menciona 3 películas donde la lesbiana NO muera al final. Si no puedes, bebe.',
        type: 'challenge',
        mode: 'statement',
        drinkTrigger: 'none',
    },
    {
        id: 'pop15',
        text: 'Bebe si tienes un crush con Cate Blanchett.',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'always',
    },
    {
        id: 'pop16',
        text: 'Yo nunca he escuchado el podcast "Está el horno para bollos".',
        type: 'question',
        mode: 'binary',
        drinkTrigger: 'yes',
    },
    {
        id: 'pop17',
        text: 'Bebe si te sabes la coreografía de "SloMo" (aunque no sea bollo explícito, es cultura).',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'always',
    },
    {
        id: 'pop18',
        text: 'Dinos tu "Celebrity Crush" actual o bebe.',
        type: 'challenge',
        mode: 'statement',
        drinkTrigger: 'none',
    },
    {
        id: 'pop19',
        text: 'Bebe si has visto "La casa de papel".',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'always',
    },
    {
        id: 'pop20',
        text: 'Yo nunca he leído fanfics de alguna serie que me gustase mucho.',
        type: 'question',
        mode: 'binary',
        drinkTrigger: 'yes',
        drinkAction: 'Bebe por nerd',
    },

    // ==========================================
    // DRAMAS Y EXES (Relationships & Toxicity)
    // ==========================================
    {
        id: 'drama1',
        text: 'Bebe si tienes una ex bloqueada en todas partes.',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'always',
    },
    {
        id: 'drama2',
        text: 'Yo nunca he vuelto con una ex el mismo día que lo dejamos.',
        type: 'question',
        mode: 'binary',
        drinkTrigger: 'yes',
    },
    {
        id: 'drama3',
        text: 'Señala a la persona que crees que volvería antes con su ex. Esa persona bebe.',
        type: 'challenge',
        mode: 'statement',
        drinkTrigger: 'none',
    },
    {
        id: 'drama4',
        text: 'Bebe si has salido con alguien y luego te has hecho mejor amiga de su nueva novia.',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'always',
    },
    {
        id: 'drama5',
        text: 'Yo nunca he llorado en el transporte público por una chica.',
        type: 'question',
        mode: 'binary',
        drinkTrigger: 'yes',
    },
    {
        id: 'drama6',
        text: 'Bebe si tienes una prenda de ropa que es de tu ex y nunca devolviste.',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'always',
    },
    {
        id: 'drama7',
        text: 'Cuenta la peor excusa que te han puesto para dejarte o bebe.',
        type: 'challenge',
        mode: 'statement',
        drinkTrigger: 'none',
    },
    {
        id: 'drama8',
        text: 'Yo nunca he mirado el LinkedIn de una ex para ver qué hace con su vida.',
        type: 'question',
        mode: 'binary',
        drinkTrigger: 'yes',
        drinkAction: 'Bebe, psicópata',
    },
    {
        id: 'drama9',
        text: 'Bebe si has mantenido una relación "en secreto" (por el motivo que sea).',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'always',
    },
    {
        id: 'drama10',
        text: 'Yo nunca he escrito un poema o canción triste después de una ruptura.',
        type: 'question',
        mode: 'binary',
        drinkTrigger: 'yes',
    },
    {
        id: 'drama11',
        text: 'Bebe si alguna vez has coincidido con 2 ex en la misma fiesta.',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'always',
    },
    {
        id: 'drama12',
        text: 'Yo nunca me he liado con la ex de mi ex (el reciclaje máximo).',
        type: 'question',
        mode: 'binary',
        drinkTrigger: 'yes',
    },
    {
        id: 'drama13',
        text: 'Bebe si tu ex te sigue dando like a las historias.',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'always',
    },
    {
        id: 'drama14',
        text: 'Bebe si alguna vez te han dejado por "necesitar tiempo para encontrarse a sí misma".',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'always',
    },
    {
        id: 'drama15',
        text: 'Yo nunca he roto con alguien por mensaje de texto o WhatsApp.',
        type: 'question',
        mode: 'binary',
        drinkTrigger: 'yes',
        drinkAction: 'Bebe, cobarde',
    },
    {
        id: 'drama16',
        text: 'Bebe si has salido con alguien que triplicaba tu edad o tú triplicabas la suya.',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'always',
    },
    {
        id: 'drama17',
        text: 'Si eres amiga de TODAS tus ex, reparte 3 tragos. Eres un ser de luz (o mientes).',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'none',
    },
    {
        id: 'drama18',
        text: 'Yo nunca he tenido una discusión de pareja en Ikea.',
        type: 'question',
        mode: 'binary',
        drinkTrigger: 'yes',
    },
    {
        id: 'drama19',
        text: 'Bebe si alguna vez has dicho "nunca más me voy a enamorar" y mentiste.',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'always',
    },
    {
        id: 'drama20',
        text: '¿Quién es la más dramática del grupo? La señalada bebe.',
        type: 'challenge',
        mode: 'statement',
        drinkTrigger: 'none',
    },

    // ==========================================
    // ESTEREOTIPOS Y COSTUMBRES
    // ==========================================
    {
        id: 'stereo1',
        text: 'Bebe si conduces un coche grande (furgoneta, SUV, 4x4) o quieres uno.',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'always',
    },
    {
        id: 'stereo2',
        text: 'Yo nunca he trabajado en una cafetería, librería o tienda de plantas.',
        type: 'question',
        mode: 'binary',
        drinkTrigger: 'yes',
    },
    {
        id: 'stereo3',
        text: 'Bebe si llevas un corte de pelo "Undercut" o "Mullet" ahora mismo.',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'always',
    },
    {
        id: 'stereo4',
        text: 'Si eres capaz de montar un mueble tú sola, manda beber a 2 personas.',
        type: 'challenge',
        mode: 'statement',
        drinkTrigger: 'none',
    },
    {
        id: 'stereo5',
        text: 'Yo nunca he jugado al fútbol, rugby o baloncesto federado.',
        type: 'question',
        mode: 'binary',
        drinkTrigger: 'yes',
        drinkAction: 'Bebe, deportista',
    },
    {
        id: 'stereo6',
        text: 'Bebe si tienes las manos frías ahora mismo. (Dicen que es señal de bollera).',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'always',
    },
    {
        id: 'stereo7',
        text: 'Bebe si no sabes sentarte bien en una silla.',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'always',
    },
    {
        id: 'stereo8',
        text: 'Yo nunca he tenido una obsesión insana con el humus.',
        type: 'question',
        mode: 'binary',
        drinkTrigger: 'yes',
    },
    {
        id: 'stereo9',
        text: 'Bebe si usas ropa de la sección de hombres habitualmente.',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'always',
    },
    {
        id: 'stereo10',
        text: 'Si eres vegana, manda un trago. Si eres vegetariana, media copa.',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'none',
    },
    {
        id: 'stereo11',
        text: 'Bebe si tienes un gato que se llama como un personaje famoso o tiene nombre de comida.',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'always',
    },
    {
        id: 'stereo12',
        text: 'Yo nunca he ido de camping para una primera cita.',
        type: 'question',
        mode: 'binary',
        drinkTrigger: 'yes',
    },
    {
        id: 'stereo13',
        text: 'Bebe si sabes tirar las cartas del Tarot.',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'always',
        drinkAction: 'Bebe, bruja',
    },
    {
        id: 'stereo14',
        text: 'Yo nunca he tenido el pelo de color azul, rosa o verde.',
        type: 'question',
        mode: 'binary',
        drinkTrigger: 'yes',
    },
    {
        id: 'stereo15',
        text: 'Bebe si tienes un tatuaje feminista.',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'always',
    },
    {
        id: 'stereo16',
        text: 'Bebe si tu bebida favorita es la cerveza artesana o la kombucha.',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'always',
    },
    {
        id: 'stereo17',
        text: 'Yo nunca he criticado el patriarcado en una primera cita.',
        type: 'question',
        mode: 'binary',
        drinkTrigger: 'yes',
    },
    {
        id: 'stereo18',
        text: 'Bebe si andas muy rápido. (El "Lesbian Walk").',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'always',
    },
    {
        id: 'stereo19',
        text: 'Si llevas tirantes, gorra o gorro de pescador, bebe.',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'always',
    },
    {
        id: 'stereo20',
        text: 'Yo nunca he regalado una planta a una chica que me gustaba.',
        type: 'question',
        mode: 'binary',
        drinkTrigger: 'yes',
    },

    // ==========================================
    // INTIMIDAD Y LIGOTEO (Flirting & Spicyish)
    // ==========================================
    {
        id: 'hot1',
        text: 'Bebe si alguna vez has tenido sexo en un coche.',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'always',
    },
    {
        id: 'hot2',
        text: 'Yo nunca he enviado nudes "artísticos".',
        type: 'question',
        mode: 'binary',
        drinkTrigger: 'yes',
    },
    {
        id: 'hot3',
        text: 'Bebe si te gustan las chicas mayores que tú (Daddy issues pero en bollo).',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'always',
    },
    {
        id: 'hot4',
        text: 'Yo nunca me he enrollado con alguien en el baño de un bar.',
        type: 'question',
        mode: 'binary',
        drinkTrigger: 'yes',
    },
    {
        id: 'hot5',
        text: 'Elige a alguien y mantén la mirada 10 segundos. La que se ría primero bebe.',
        type: 'challenge',
        mode: 'statement',
        drinkTrigger: 'none',
    },
    {
        id: 'hot6',
        text: 'Bebe si prefieres dar el primer paso tú.',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'always',
    },
    {
        id: 'hot7',
        text: 'Yo nunca he tenido un sueño erótico con una amiga presente.',
        type: 'question',
        mode: 'binary',
        drinkTrigger: 'yes',
        drinkAction: 'Bebe, cochina',
    },
    {
        id: 'hot8',
        text: 'Bebe si te ponen nerviosa las chicas con manos bonitas.',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'always',
    },
    {
        id: 'hot9',
        text: 'Dale un beso en la mejilla (o donde quieras) a la persona de tu izquierda. Si no, bebe.',
        type: 'challenge',
        mode: 'statement',
        drinkTrigger: 'none',
    },
    {
        id: 'hot10',
        text: 'Yo nunca he usado una app de ligar solo para validar mi ego.',
        type: 'question',
        mode: 'binary',
        drinkTrigger: 'yes',
    },
    {
        id: 'hot11',
        text: 'Bebe si has tenido sexo escuchando Girl in Red o The Weeknd.',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'always',
    },
    {
        id: 'hot12',
        text: 'Manda un mensaje picante a tu último match de Tinder/Bumble/Her. O bebe 2 tragos.',
        type: 'challenge',
        mode: 'statement',
        drinkTrigger: 'none',
    },
    {
        id: 'hot13',
        text: 'Bebe si alguna vez te han pillado haciéndolo (padres, compis de piso...).',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'always',
    },
    {
        id: 'hot14',
        text: 'Yo nunca he fingido un orgasmo... con una mujer.',
        type: 'question',
        mode: 'binary',
        drinkTrigger: 'yes',
    },
    {
        id: 'hot15',
        text: 'Bebe si te gusta que te agarren del pelo.',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'always',
    },
    {
        id: 'hot16',
        text: 'Describe tu técnica infalible para ligar en 3 palabras.',
        type: 'challenge',
        mode: 'statement',
        drinkTrigger: 'none',
    },
    {
        id: 'hot17',
        text: 'Yo nunca he dudado si era una cita o una salida de amigas hasta el final.',
        type: 'question',
        mode: 'binary',
        drinkTrigger: 'yes',
    },
    {
        id: 'hot18',
        text: 'Bebe si tienes un juguete sexual favorito y le tienes nombre.',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'always',
    },
    {
        id: 'hot19',
        text: 'Di qué es lo primero que te fijas en una chica. Si es el culo/pecho, bebe.',
        type: 'challenge',
        mode: 'statement',
        drinkTrigger: 'none',
    },
    {
        id: 'hot20',
        text: 'Bebe si alguna vez te has liado con una hetero "curiosa".',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'always',
    },

    // ==========================================
    // DEBATES ABSURDOS & RANDOM
    // ==========================================
    {
        id: 'deb1',
        text: '¿Gatos o Perros? Las de Gatos beben 1, las de Perros beben 2 (por básicas).',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'always',
    },
    {
        id: 'deb2',
        text: '¿Playa o Montaña? Quien pierda la votación bebe.',
        type: 'challenge',
        mode: 'statement',
        drinkTrigger: 'none',
    },
    {
        id: 'deb3',
        text: 'Si crees que el horóscopo es real, bebe. Si crees que es una estafa, ríete de las que beben.',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'always',
    },
    {
        id: 'deb4',
        text: '¿Pizza con piña? Si te gusta, bebe y sal de la habitación un momento.',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'none',
    },
    {
        id: 'deb5',
        text: 'Que levante la mano quien se haya liado con más de 10 personas. Esas beben.',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'none',
    },
    {
        id: 'deb6',
        text: 'Bebe si has visto todos los capítulos de Harry Potter pero ahora odias a la autora.',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'always',
    },
    {
        id: 'deb7',
        text: '¿Debería volver con mi ex? Si el grupo grita NO, bebes tú. Si grita SÍ, beben ellas.',
        type: 'challenge',
        mode: 'statement',
        drinkTrigger: 'none',
    },
    {
        id: 'deb8',
        text: 'Bebe si alguna vez has dicho "uwu" en la vida real no irónicamente.',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'always',
    },
    {
        id: 'deb9',
        text: 'Si usas gafas, bebe. Si son de pasta gorda, bebe doble.',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'always',
    },
    {
        id: 'deb10',
        text: 'Bebe si tienes la app de ligar instalada.',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'always',
    },
    {
        id: 'deb11',
        text: 'Yo nunca he mentido en este juego.',
        type: 'question',
        mode: 'binary',
        drinkTrigger: 'yes',
        drinkAction: '¡Mentirosa!',
    },
    {
        id: 'deb12',
        text: 'Bebe si hoy llevas ropa interior que no hace conjunto.',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'always',
    },
    {
        id: 'deb13',
        text: 'Beben todas las que han ido a una fiesta o actividad de LesGirls.',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'always',
    },

    // ==========================================
    // VIDA DOMÉSTICA (Moving in, Pets, Ikea)
    // ==========================================
    {
        id: 'dom1',
        text: 'Bebe si compartes cuenta de Netflix, Spotify o HBO con tu ex.',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'always',
    },
    {
        id: 'dom2',
        text: 'Yo nunca he adoptado una mascota con una pareja y luego me la quedé yo.',
        type: 'question',
        mode: 'binary',
        drinkTrigger: 'yes',
        drinkAction: 'Bebe por madre soltera',
    },
    {
        id: 'dom3',
        text: 'Si tienes más de 5 plantas en tu habitación/salón, reparte 2 tragos.',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'none',
    },
    {
        id: 'dom4',
        text: 'Bebe si has discutido por quién lava los platos o saca la basura.',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'always',
    },
    {
        id: 'dom5',
        text: 'Yo nunca he comprado muebles de segunda mano para mi piso de bolleras.',
        type: 'question',
        mode: 'binary',
        drinkTrigger: 'yes',
    },
    {
        id: 'dom6',
        text: 'Bebe si tu casa huele a incienso, palo santo o velas caras.',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'always',
    },
    {
        id: 'dom7',
        text: '¿Quién es la "madre" del grupo? La señalada bebe.',
        type: 'challenge',
        mode: 'statement',
        drinkTrigger: 'none',
    },
    {
        id: 'dom8',
        text: 'Yo nunca he convivido con una ex porque "el alquiler es muy caro".',
        type: 'question',
        mode: 'binary',
        drinkTrigger: 'yes',
        drinkAction: 'Bebe por crisis de vivienda',
    },
    {
        id: 'dom9',
        text: 'Bebe si tienes un cajón de "cosas varias" (cables, tornillos, llaves que no sabes de qué son).',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'always',
    },
    {
        id: 'dom10',
        text: 'Descalzate. Si llevas calcetines con dibujos o de colores, bebes.',
        type: 'challenge',
        mode: 'statement',
        drinkTrigger: 'none',
    },

    // ==========================================
    // ASTROLOGÍA AVANZADA (The Zodiac Roast)
    // ==========================================
    {
        id: 'astro1',
        text: 'Si eres Escorpio o Géminis, bebe 2 tragos. Lo siento, es la ley.',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'always',
    },
    {
        id: 'astro2',
        text: 'Bebe si tienes la luna en un signo de agua (Cáncer, Escorpio, Piscis). Dramáticas.',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'always',
    },
    {
        id: 'astro3',
        text: 'Yo nunca he culpado a "Mercurio Retrógrado" de mis malas decisiones.',
        type: 'question',
        mode: 'binary',
        drinkTrigger: 'yes',
    },
    {
        id: 'astro4',
        text: 'Las de signos de Fuego (Aries, Leo, Sagitario) mandan beber a las de Tierra (Tauro, Virgo, Capricornio).',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'none',
    },
    {
        id: 'astro5',
        text: 'Bebe si sabes tu hora exacta de nacimiento de memoria.',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'always',
    },
    {
        id: 'astro6',
        text: 'Si eres Libra, no puedes decidir quién bebe. Bebe tú por indecisa.',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'always',
    },
    {
        id: 'astro7',
        text: 'Yo nunca he preguntado el signo a alguien antes de saber su apellido.',
        type: 'question',
        mode: 'binary',
        drinkTrigger: 'yes',
    },
    {
        id: 'astro8',
        text: 'Bebe si tienes una app de astrología y has pagado la versión premium.',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'always',
    },

    // ==========================================
    // CULTURA QUEER DEEP CUTS (Música y Referencias)
    // ==========================================
    {
        id: 'deep1',
        text: 'Bebe si has visto alguna vez a Rosalia en vivo.',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'always',
    },
    {
        id: 'deep2',
        text: 'Yo nunca he ido a un concierto de Lady Gaga.',
        type: 'question',
        mode: 'binary',
        drinkTrigger: 'yes',
    },
    {
        id: 'deep3',
        text: 'Si sabes quién es "Sandra Barneda", reparte 2 tragos. Taste.',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'none',
    },
    {
        id: 'deep4',
        text: 'Bebe si has visto Vis a Vis.',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'always',
    },
    {
        id: 'deep5',
        text: 'Yo nunca he tenido un corte de pelo inspirado en alguna lesbiana famosa.',
        type: 'question',
        mode: 'binary',
        drinkTrigger: 'yes',
    },
    {
        id: 'deep6',
        text: 'Bebe si sabes decir algun grupo de música que alguna de las componentes sea lesbiana.',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'always',
    },
    {
        id: 'deep7',
        text: 'Cita una frase icónica de "Los Simpson".',
        type: 'challenge',
        mode: 'statement',
        drinkTrigger: 'none',
    },
    {
        id: 'deep8',
        text: 'Bebe si te has sentido identificada con "Villanelle" (Killing Eve). Preocupante.',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'always',
    },
    {
        id: 'deep9',
        text: 'Yo nunca he tenido una discusión sobre si Taylor Swift es fruity o no.',
        type: 'question',
        mode: 'binary',
        drinkTrigger: 'yes',
        drinkAction: 'Bebe, Gaylor',
    },
    {
        id: 'deep10',
        text: 'Bebe si tu outfit de hoy parece sacado de un videoclip indie.',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'always',
    },

    // ==========================================
    // SITUACIONES INCÓMODAS
    // ==========================================
    {
        id: 'awk1',
        text: 'Bebe si alguna vez te han preguntado "¿quién hace de hombre?" y has tenido que sonreír.',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'always',
    },
    {
        id: 'awk2',
        text: 'Yo nunca he tenido que salir del armario con la misma persona dos veces porque se le olvidó.',
        type: 'question',
        mode: 'binary',
        drinkTrigger: 'yes',
    },
    {
        id: 'awk3',
        text: 'Bebe si tu familia cree que tu novia es "tu amiga que se queda a dormir mucho".',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'always',
    },
    {
        id: 'awk4',
        text: 'Cuenta tu momento "Gay Panic" más vergonzoso o bebe.',
        type: 'challenge',
        mode: 'statement',
        drinkTrigger: 'none',
    },
    {
        id: 'awk5',
        text: 'Yo nunca he mirado a una chica heterosexual y pensado "puedo cambiarla".',
        type: 'question',
        mode: 'binary',
        drinkTrigger: 'yes',
        drinkAction: 'Bebe, ilusa',
    },
    {
        id: 'awk6',
        text: 'Bebe si te has encontrado a tu profesora/jefa en un bar de ambiente.',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'always',
    },
    {
        id: 'awk7',
        text: 'Si alguna vez te han dicho "es que eres muy guapa para ser lesbiana", bebe de rabia.',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'always',
    },
    {
        id: 'awk8',
        text: 'Yo nunca he tenido que explicar lo que es una "tijera" a un hombre hetero.',
        type: 'question',
        mode: 'binary',
        drinkTrigger: 'yes',
    },
    {
        id: 'awk9',
        text: 'Bebe si en tu familia hay otra persona queer y hay "competencia".',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'always',
    },
    {
        id: 'awk10',
        text: 'Brindad por sobrevivir a la adolescencia. ¡Todas beben!',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'always',
    },

    // ==========================================
    // CARTAS ESPECIALES (Mecánicas de Juego)
    // ==========================================
    {
        id: 'special1',
        text: '🔥 ¡DOBLE PUNTOS! La siguiente ronda vale el doble.',
        type: 'rule',
        mode: 'rule',
        drinkTrigger: 'none',
        points: 2,
        specialEffect: 'double',
    },
    {
        id: 'special2',
        text: '🔄 ¡CAMBIO DE SENTIDO! El orden del juego se invierte.',
        type: 'rule',
        mode: 'rule',
        drinkTrigger: 'none',
        points: 1,
        specialEffect: 'reverse',
    },
    {
        id: 'special3',
        text: '⏭️ VETO: La siguiente jugadora pierde su turno.',
        type: 'challenge',
        mode: 'statement',
        drinkTrigger: 'none',
        points: 2,
        specialEffect: 'skip',
    },
    {
        id: 'special4',
        text: '💰 ROBO: Elige a una jugadora y róbale 10 puntos.',
        type: 'challenge',
        mode: 'statement',
        drinkTrigger: 'none',
        points: 0,
        specialEffect: 'steal',
    },
    {
        id: 'special5',
        text: '⚡ BONUS: Ganas 5 puntos extra. ¡Suerte!',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'none',
        points: 5,
    },
    {
        id: 'special6',
        text: '🔥 ¡DOBLE PUNTOS! La siguiente ronda vale el doble.',
        type: 'rule',
        mode: 'rule',
        drinkTrigger: 'none',
        points: 2,
        specialEffect: 'double',
    },
    {
        id: 'special7',
        text: '🔄 ¡CAMBIO DE SENTIDO! El orden del juego se invierte.',
        type: 'rule',
        mode: 'rule',
        drinkTrigger: 'none',
        points: 1,
        specialEffect: 'reverse',
    },
    {
        id: 'special8',
        text: '⏭️ VETO: La siguiente jugadora pierde su turno.',
        type: 'challenge',
        mode: 'statement',
        drinkTrigger: 'none',
        points: 2,
        specialEffect: 'skip',
    },
    {
        id: 'special9',
        text: '💰 ROBO: Elige a una jugadora y róbale 10 puntos.',
        type: 'challenge',
        mode: 'statement',
        drinkTrigger: 'none',
        points: 0,
        specialEffect: 'steal',
    },
    {
        id: 'special10',
        text: '⚡ MEGA BONUS: Ganas 10 puntos extra. ¡Jackpot!',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'none',
        points: 10,
    },
    {
        id: 'special11',
        text: '🎲 RULETA: Tira una moneda. Cara = 5 puntos, Cruz = pierdes 5 puntos.',
        type: 'challenge',
        mode: 'statement',
        drinkTrigger: 'none',
        points: 0,
    },
    {
        id: 'special12',
        text: '🔥 ¡DOBLE PUNTOS! La siguiente ronda vale el doble.',
        type: 'rule',
        mode: 'rule',
        drinkTrigger: 'none',
        points: 2,
        specialEffect: 'double',
    },
    {
        id: 'special13',
        text: '🔄 ¡CAMBIO DE SENTIDO! El orden del juego se invierte.',
        type: 'rule',
        mode: 'rule',
        drinkTrigger: 'none',
        points: 1,
        specialEffect: 'reverse',
    },
    {
        id: 'special14',
        text: '⏭️ VETO: La siguiente jugadora pierde su turno.',
        type: 'challenge',
        mode: 'statement',
        drinkTrigger: 'none',
        points: 2,
        specialEffect: 'skip',
    },
    {
        id: 'special15',
        text: '💰 ROBO: Elige a una jugadora y róbale 10 puntos.',
        type: 'challenge',
        mode: 'statement',
        drinkTrigger: 'none',
        points: 0,
        specialEffect: 'steal',
    },
    {
        id: 'special16',
        text: '🎁 REGALO: Regala 5 puntos a la jugadora que elijas.',
        type: 'challenge',
        mode: 'statement',
        drinkTrigger: 'none',
        points: 1,
    },
    {
        id: 'special17',
        text: '💥 BOMBA: Todas pierden 3 puntos excepto tú.',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'none',
        points: 3,
    },
    {
        id: 'special18',
        text: '🌟 ESTRELLA: Duplica tus puntos actuales si tienes menos de 20.',
        type: 'viral',
        mode: 'statement',
        drinkTrigger: 'none',
        points: 0,
    },
    {
        id: 'special19',
        text: '🔥 ¡DOBLE PUNTOS! La siguiente ronda vale el doble.',
        type: 'rule',
        mode: 'rule',
        drinkTrigger: 'none',
        points: 2,
        specialEffect: 'double',
    },
    {
        id: 'special20',
        text: '🔄 ¡CAMBIO DE SENTIDO! El orden del juego se invierte.',
        type: 'rule',
        mode: 'rule',
        drinkTrigger: 'none',
        points: 1,
        specialEffect: 'reverse',
    },

    // === NUEVAS CARTAS ORIGINALES ===

    // Yo Nunca - Experiencias únicas
    {
        id: 'yn_new1',
        text: 'Yo nunca he tenido un crush con una profesora.',
        type: 'question',
        mode: 'binary',
        drinkTrigger: 'yes',
    },
    {
        id: 'yn_new2',
        text: 'Yo nunca he llorado viendo un vídeo de propuesta de matrimonio lésbica.',
        type: 'question',
        mode: 'binary',
        drinkTrigger: 'yes',
    },
    {
        id: 'yn_new3',
        text: 'Yo nunca he tenido una cita en un museo.',
        type: 'question',
        mode: 'binary',
        drinkTrigger: 'yes',
    },
    {
        id: 'yn_new4',
        text: 'Yo nunca he escrito poesía para alguien que me gustaba.',
        type: 'question',
        mode: 'binary',
        drinkTrigger: 'yes',
    },
    {
        id: 'yn_new5',
        text: 'Yo nunca he tenido miedo de salir del armario con mi familia.',
        type: 'question',
        mode: 'binary',
        drinkTrigger: 'yes',
    },
    {
        id: 'yn_new6',
        text: 'Yo nunca he ido a una marcha del orgullo.',
        type: 'question',
        mode: 'binary',
        drinkTrigger: 'yes',
    },
    {
        id: 'yn_new7',
        text: 'Yo nunca he tenido un sueño erótico con una celebrity.',
        type: 'question',
        mode: 'binary',
        drinkTrigger: 'yes',
    },
    {
        id: 'yn_new8',
        text: 'Yo nunca he cancelado planes para quedarme en casa viendo series lésbicas.',
        type: 'question',
        mode: 'binary',
        drinkTrigger: 'yes',
    },
    {
        id: 'yn_new9',
        text: 'Yo nunca he stalkeado el Instagram de mi ex durante horas.',
        type: 'question',
        mode: 'binary',
        drinkTrigger: 'yes',
    },
    {
        id: 'yn_new10',
        text: 'Yo nunca he tenido una relación a distancia.',
        type: 'question',
        mode: 'binary',
        drinkTrigger: 'yes',
    },

    // Retos creativos
    {
        id: 'reto_new1',
        text: 'Cuenta tu peor experiencia en una primera cita.',
        type: 'challenge',
        mode: 'statement',
        drinkTrigger: 'always',
    },
    {
        id: 'reto_new2',
        text: 'Imita cómo camina tu crush.',
        type: 'challenge',
        mode: 'statement',
        drinkTrigger: 'always',
    },
    {
        id: 'reto_new3',
        text: 'Di el nombre de tu primer amor y por qué te gustaba.',
        type: 'challenge',
        mode: 'statement',
        drinkTrigger: 'always',
    },
    {
        id: 'reto_new4',
        text: 'Envía un mensaje de voz a tu ex diciendo "te echo de menos" (o bebe 3 veces).',
        type: 'challenge',
        mode: 'statement',
        drinkTrigger: 'always',
    },
    {
        id: 'reto_new5',
        text: 'Muestra la última foto que le enviaste a tu crush.',
        type: 'challenge',
        mode: 'statement',
        drinkTrigger: 'always',
    },
    {
        id: 'reto_new6',
        text: 'Cuenta tu fantasía más atrevida (o bebe).',
        type: 'challenge',
        mode: 'statement',
        drinkTrigger: 'always',
    },
    {
        id: 'reto_new7',
        text: 'Haz un piropo a la jugadora de tu izquierda.',
        type: 'challenge',
        mode: 'statement',
        drinkTrigger: 'none',
    },
    {
        id: 'reto_new8',
        text: 'Baila reggaeton durante 30 segundos.',
        type: 'challenge',
        mode: 'statement',
        drinkTrigger: 'none',
    },
    {
        id: 'reto_new9',
        text: 'Di tres cosas que te atraen de las mujeres.',
        type: 'challenge',
        mode: 'statement',
        drinkTrigger: 'none',
    },
    {
        id: 'reto_new10',
        text: 'Cuenta la historia más vergonzosa que te haya pasado ligando.',
        type: 'challenge',
        mode: 'statement',
        drinkTrigger: 'always',
    },

    // Afirmaciones picantes
    {
        id: 'afirm_new1',
        text: 'La jugadora con el pelo más largo bebe.',
        type: 'rule',
        mode: 'statement',
        drinkTrigger: 'always',
    },
    {
        id: 'afirm_new2',
        text: 'Todas las que tengan tatuajes beben.',
        type: 'rule',
        mode: 'statement',
        drinkTrigger: 'always',
    },
    {
        id: 'afirm_new3',
        text: 'La que haya tenido más relaciones bebe el doble.',
        type: 'rule',
        mode: 'statement',
        drinkTrigger: 'always',
    },
    {
        id: 'afirm_new4',
        text: 'Si llevas ropa interior negra, bebe.',
        type: 'rule',
        mode: 'statement',
        drinkTrigger: 'always',
    },
    {
        id: 'afirm_new5',
        text: 'La última en haber besado a alguien bebe.',
        type: 'rule',
        mode: 'statement',
        drinkTrigger: 'always',
    },

    // Más Yo Nunca específicos
    {
        id: 'yn_new11',
        text: 'Yo nunca he tenido un lío en un baño de bar.',
        type: 'question',
        mode: 'binary',
        drinkTrigger: 'yes',
    },
    {
        id: 'yn_new12',
        text: 'Yo nunca he mandado nudes a alguien que acababa de conocer.',
        type: 'question',
        mode: 'binary',
        drinkTrigger: 'yes',
    },
    {
        id: 'yn_new13',
        text: 'Yo nunca he tenido sexo en un coche.',
        type: 'question',
        mode: 'binary',
        drinkTrigger: 'yes',
    },
    {
        id: 'yn_new14',
        text: 'Yo nunca he fingido un orgasmo.',
        type: 'question',
        mode: 'binary',
        drinkTrigger: 'yes',
    },
    {
        id: 'yn_new15',
        text: 'Yo nunca he tenido un trío.',
        type: 'question',
        mode: 'binary',
        drinkTrigger: 'yes',
    },
    {
        id: 'yn_new16',
        text: 'Yo nunca he usado juguetes sexuales con mi pareja.',
        type: 'question',
        mode: 'binary',
        drinkTrigger: 'yes',
    },
    {
        id: 'yn_new17',
        text: 'Yo nunca he tenido una relación abierta.',
        type: 'question',
        mode: 'binary',
        drinkTrigger: 'yes',
    },
    {
        id: 'yn_new18',
        text: 'Yo nunca he ido a un club lésbico.',
        type: 'question',
        mode: 'binary',
        drinkTrigger: 'yes',
    },
    {
        id: 'yn_new19',
        text: 'Yo nunca he tenido una relación con alguien del trabajo.',
        type: 'question',
        mode: 'binary',
        drinkTrigger: 'yes',
    },
    {
        id: 'yn_new20',
        text: 'Yo nunca he ghosteado a alguien después de una cita.',
        type: 'question',
        mode: 'binary',
        drinkTrigger: 'yes',
    },
];
